const TRUTH_CHALLENGES = [
    "Crush hiện tại của bạn là ai trong phòng?",
    "Kể về kỷ niệm xấu hổ nhất của bạn",
    "Điều bí mật mà bạn chưa kể cho ai?",
    "Bạn thích ai nhất trong phòng này và tại sao?",
    "Lần cuối bạn khóc là khi nào và vì sao?",
    "Điều gì bạn muốn thay đổi ở bản thân?",
    "Bạn đã từng nói dối gì lớn nhất?",
    "First impression của bạn về người bên cạnh?",
    "Điều bạn sợ nhất là gì?",
    "Nếu được một điều ước, bạn sẽ ước gì?",
    "Bạn đã từng thích ai trong club chưa?",
    "Mô tả typical của bạn trong 3 từ?",
    "Điều gì khiến bạn tự tin nhất về bản thân?",
    "Bạn có từng stalk ai trên mạng xã hội không?",
    "Lần gần nhất bạn cảm thấy tự hào về bản thân?",
    "Bạn có bí mật nào về công việc/học tập không?",
    "Nếu phải chọn 1 người trong phòng đi du lịch, bạn chọn ai?",
    "Điều bạn hối hận nhất trong cuộc sống?",
    "Thói quen xấu mà bạn đang cố bỏ?",
    "Bạn có từng crush người lớn tuổi hơn nhiều không?",
    "Điều gì bạn thấy khó chịu nhất ở người khác?",
    "Kể về lần bạn bị từ chối đau nhất?",
    "Bạn nghĩ ai trong phòng này sẽ thành công nhất?",
    "Điều gì làm bạn mất ngủ gần đây?",
    "Bạn có từng làm điều gì mà bố mẹ không biết?",
];

const DARE_CHALLENGES = [
    "Tỏ tình với người ngồi bên cạnh bạn (diễn thật tâm nhé!)",
    "Gọi điện cho người cuối cùng trong danh bạ và hát 1 câu",
    "Nhảy 1 điệu dance TikTok ngay bây giờ",
    "Làm mặt cute nhất có thể và giữ 10 giây",
    "Nói 'I love you' bằng 5 ngôn ngữ khác nhau",
    "Đọc tin nhắn gần nhất trong điện thoại cho mọi người nghe",
    "Bắt chước một người trong phòng, để mọi người đoán",
    "Hát một đoạn bài hát mà không được mở nhạc",
    "Làm điệu bộ tỏ tình như trong phim Hàn",
    "Đăng story Instagram khen người bên cạnh",
    "Nhắn tin 'Em nhớ anh/Em nhớ chị' cho người cuối cùng nhắn tin",
    "Để người bên cạnh style lại tóc cho bạn",
    "Gọi 1 ai đó và nói bạn đang nghĩ về họ",
    "Làm 10 cái chống đẩy ngay bây giờ",
    "Nhại lại giọng người ngồi đối diện",
    "Pose ảnh selfie kiểu ngầu nhất và đăng story",
    "Kể 1 kỷ niệm vui với người bên cạnh",
    "Hát bài 'Happy Birthday' cho người đối diện",
    "Nói lời cảm ơn chân thành với 1 người trong phòng",
    "Làm mặt giận dữ và hỏi 'Sao dám nhìn tui?'",
    "Đọc 1 bài thơ tình cho người bên cạnh",
    "Khen 3 điều về 3 người khác nhau trong phòng",
    "Để người khác chụp ảnh và đăng lên (ảnh nghiêm túc nhé)",
    "Thử thách giữ mặt nghiêm khi mọi người cố làm bạn cười",
    "Nhảy sexy dance 10 giây (trong khuôn khổ cho phép)",
];
