const TRUTH_CHALLENGES = [
    "Crush hiện tại của bạn là ai trong phòng?",
    "Kể về kỷ niệm xấu hổ nhất của bạn",
    "Điều bí mật mà bạn chưa kể cho ai?",
    "Bạn thích ai nhất trong phòng này và tại sao?",
    "Lần cuối bạn khóc là khi nào và vì sao?",
    "Điều gì bạn muốn thay đổi ở bản thân?",
    "Bạn đã từng nói dối gì lớn nhất?",
    "First impression của bạn về người bên cạnh?",
    "Điều bạn sợ nhất là gì?",
    "Nếu được một điều ước, bạn sẽ ước gì?",
    "Bạn đã từng thích ai trong club chưa?",
    "Mô tả type của bạn trong 3 từ?",
    "Điều gì khiến bạn tự tin nhất về bản thân?",
    "Bạn có từng stalk ai trên mạng xã hội không?",
    "Lần gần nhất bạn cảm thấy tự hào về bản thân?",
    "Bạn có bí mật nào về công việc/học tập không?",
    "Nếu phải chọn 1 người trong phòng đi du lịch, bạn chọn ai?",
    "Điều bạn hối hận nhất trong cuộc sống?",
    "Thói quen xấu mà bạn đang cố bỏ?",
    "Bạn có từng crush người lớn tuổi hơn nhiều không?",
    "Điều gì bạn thấy khó chịu nhất ở người khác?",
    "Kể về lần bạn bị từ chối đau nhất?",
    "Bạn nghĩ ai trong phòng này sẽ thành công nhất?",
    "Điều gì làm bạn mất ngủ gần đây?",
    "Bạn có từng làm điều gì mà bố mẹ không biết?",
    "Món ăn Việt Nam nào bạn thầm ghét dù ai cũng thích?",
    "Kể về một hiểu lầm buồn cười nhất của bạn?",
    "Tài năng bí mật nào mà không ai biết?",
    "Nếu đổi đời với ai trong gia đình 1 ngày, bạn chọn ai?",
    "Quà Tết kỳ lạ nhất bạn từng nhận là gì?",
    "Câu nói hay thành ngữ tiếng Việt nào bạn thấy hài nhất?",
    "Lời khuyên nào từ cha mẹ bạn vẫn nhớ đến giờ?",
    "Ước mơ thời nhỏ nào bạn chưa thực hiện được?",
    "Truyền thống Việt Nam nào bạn tự hào nhất?",
    "Kỷ niệm sum họp gia đình đáng nhớ nhất?",
    "Bạn học được gì từ người lớn tuổi mà thấy quý giá?",
    "Ai trong phòng có vibe giống crush cũ của bạn nhất?",
    "Nếu được hẹn hò ai trong phòng, bạn chọn ai?",
    "Tin nhắn gần nhất bạn gửi đi nói gì?",
    "Điều gì về văn hóa Việt Nam khiến bạn tự hào?",
];

const DARE_CHALLENGES = [
    "Tỏ tình với người ngồi bên cạnh bạn (diễn thật tâm nhé!)",
    "Gọi điện cho người cuối cùng trong danh bạ và hát 1 câu",
    "Nhảy 1 điệu dance TikTok ngay bây giờ",
    "Làm mặt cute nhất có thể và giữ 10 giây",
    "Nói 'I love you' bằng 5 ngôn ngữ khác nhau",
    "Đọc tin nhắn gần nhất trong điện thoại cho mọi người nghe",
    "Bắt chước một người trong phòng, để mọi người đoán",
    "Hát một đoạn bài hát mà không được mở nhạc",
    "Làm điệu bộ tỏ tình như trong phim Hàn",
    "Đăng story Instagram khen người bên cạnh",
    "Nhắn tin 'Em nhớ anh/Em nhớ chị' cho người cuối cùng nhắn tin",
    "Để người bên cạnh style lại tóc cho bạn",
    "Gọi 1 ai đó và nói bạn đang nghĩ về họ",
    "Làm 10 cái chống đẩy ngay bây giờ",
    "Nhại lại giọng người ngồi đối diện",
    "Pose ảnh selfie kiểu ngầu nhất và đăng story",
    "Kể 1 kỷ niệm vui với người bên cạnh",
    "Hát bài 'Happy Birthday' cho người đối diện",
    "Nói lời cảm ơn chân thành với 1 người trong phòng",
    "Làm mặt giận dữ và hỏi 'Sao dám nhìn tui?'",
    "Đọc 1 bài thơ tình cho người bên cạnh",
    "Khen 3 điều về 3 người khác nhau trong phòng",
    "Để người khác chụp ảnh và đăng lên (ảnh nghiêm túc nhé)",
    "Thử thách giữ mặt nghiêm khi mọi người cố làm bạn cười",
    "Nhảy sexy dance 10 giây (trong khuôn khổ cho phép)",
    "Hát karaoke 1 đoạn bài hát Việt Nam nổi tiếng",
    "Dạy mọi người 1 câu tiếng Việt với đúng thanh điệu",
    "Bắt chước nhân vật truyền thống Việt Nam (múa rồng, khỉ...)",
    "Ăn 1 miếng trái cây chỉ bằng đũa",
    "Đọc 1 câu tục ngữ hoặc tự sáng tác 1 câu hài hước",
    "Đi kiểu 'silly walk' quanh phòng theo yêu cầu của nhóm",
    "Nhắm mắt đoán trái cây hoặc thảo mộc qua mùi",
    "Khen tất cả mọi người trong phòng bằng tiếng Việt",
    "Diễn lại hoạt động thường ngày bằng cử chỉ (nấu phở, đi xe máy...)",
    "Tạo 1 bài chúc mừng tiếng Việt cho tình bạn hoặc may mắn",
    "Kể chuyện ngẫu hứng với người khác, mỗi người 1 câu",
    "Nếu có nhạc, dẫn đầu nhóm nhảy trong 30 giây",
    "Làm mặt seducing nhìn người đối diện 5 giây",
    "Cho mọi người xem 3 ảnh gần nhất trong thư viện ảnh",
    "Mở Instagram và like 5 bài post gần nhất của người bên cạnh",
];
